# Generated by Django 5.2.7 on 2025-12-23 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_CALL', 'On Call'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('current_patient_count', models.IntegerField(default=0)),
                ('accepts_specializations', models.JSONField(blank=True, default=list)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.OneToOneField(limit_choices_to={'role': 'CLINICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clinician Availability',
            },
        ),
        migrations.CreateModel(
            name='ClinicianAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ASSESSMENT_VIEWED', 'Assessment Viewed'), ('ASSESSMENT_REVIEWED', 'Assessment Reviewed'), ('ASSESSMENT_APPROVED', 'Assessment Approved'), ('ASSESSMENT_MODIFIED', 'Assessment Modified'), ('ASSESSMENT_REJECTED', 'Assessment Rejected'), ('ASSESSMENT_SENT', 'Assessment Sent to Patient'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_RECEIVED', 'Message Received'), ('PATIENT_ASSIGNED', 'Patient Assigned'), ('ESCALATION_HANDLED', 'Escalation Handled'), ('AVAILABILITY_UPDATED', 'Availability Updated')], max_length=30)),
                ('action_details', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clinician', models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_actions', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_actions', to='conversations.conversationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['clinician', 'timestamp'], name='clinician_c_clinici_621f10_idx'), models.Index(fields=['action_type', 'timestamp'], name='clinician_c_action__52665e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('assignment_reason', models.CharField(choices=[('AUTO_MATCH', 'Automatic Match'), ('ESCALATION', 'Escalation'), ('MANUAL', 'Manual Assignment'), ('SPECIALIST_REFERRAL', 'Specialist Referral'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assignments', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conversations.conversationsession')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_assignments', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['clinician', 'status'], name='clinician_p_clinici_9d7839_idx'), models.Index(fields=['patient', 'status'], name='clinician_p_patient_e3aff9_idx')],
            },
        ),
    ]
