# Generated by Django 5.2.7 on 2025-12-27 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('clinician', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20)),
                ('current_step', models.CharField(choices=[('MEDICATIONS', 'Medications'), ('RECOMMENDATIONS', 'Recommendations'), ('MONITORING', 'Monitoring Advice'), ('NOTES', "Doctor's Note"), ('CONFIRM', 'Confirmation')], default='MEDICATIONS', max_length=20)),
                ('modified_otc_suggestions', models.JSONField(blank=True, null=True)),
                ('modified_recommendations', models.JSONField(blank=True, null=True)),
                ('modified_monitoring_advice', models.JSONField(blank=True, null=True)),
                ('clinician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_sessions', to='assessments.aiassessment')),
                ('clinician', models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='modification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinician', 'status'], name='clinician_m_clinici_980d46_idx'), models.Index(fields=['assessment', 'status'], name='clinician_m_assessm_4c0357_idx')],
            },
        ),
    ]
