# Generated by Django 5.2.7 on 2025-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0002_modificationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationsession',
            name='sent_with_warnings',
            field=models.BooleanField(default=False, help_text='Was this sent despite validation warnings?'),
        ),
        migrations.AddField(
            model_name='modificationsession',
            name='validation_result',
            field=models.JSONField(blank=True, help_text='Result from AI validator', null=True),
        ),
        migrations.AddField(
            model_name='modificationsession',
            name='warning_override_reason',
            field=models.TextField(blank=True, help_text='Why clinician overrode warnings'),
        ),
    ]
