# Generated by Django 5.2.7 on 2025-12-23 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('RED_FLAG_SYMPTOM', 'Red Flag Symptom'), ('SEVERITY_THRESHOLD', 'Severity Threshold'), ('RESPONSE_SLA_BREACH', 'Response SLA Breach'), ('CLINICIAN_UNAVAILABLE', 'Clinician Unavailable'), ('MANUAL_REQUEST', 'Manual Request'), ('PATIENT_FOLLOW_UP', 'Patient Follow-up Required')], max_length=30)),
                ('trigger_keywords', models.JSONField(blank=True, default=list)),
                ('severity_threshold', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('IMMEDIATE_ALERT', 'Immediate Alert'), ('QUEUE_PRIORITY', 'Queue Priority'), ('SUPERVISOR_ALERT', 'Supervisor Alert'), ('EMERGENCY_PROTOCOL', 'Emergency Protocol'), ('AUTO_TRANSFER', 'Auto Transfer')], max_length=30)),
                ('action_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('HANDLED', 'Handled'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('alert_message', models.TextField()),
                ('alert_severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('triggered_by_keyword', models.CharField(blank=True, max_length=200)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_alerts', to='conversations.conversationsession')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_escalations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='escalations.escalationrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_changes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='conversations.conversationsession')),
                ('escalation_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='escalations.escalationalert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='escalationalert',
            index=models.Index(fields=['alert_status', 'triggered_at'], name='escalations_alert_s_c02e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationalert',
            index=models.Index(fields=['conversation', 'alert_status'], name='escalations_convers_d771e2_idx'),
        ),
    ]
