# Generated by Django 5.2.7 on 2025-12-23 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_age', models.IntegerField(null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20)),
                ('chief_complaint', models.TextField()),
                ('symptoms_overview', models.JSONField(blank=True, default=dict)),
                ('key_observations', models.JSONField(blank=True, default=dict)),
                ('preliminary_recommendations', models.JSONField(blank=True, default=dict)),
                ('otc_suggestions', models.JSONField(blank=True, default=dict)),
                ('monitoring_advice', models.JSONField(blank=True, default=dict)),
                ('red_flags_detected', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('MODIFIED', 'Modified'), ('REJECTED', 'Rejected'), ('SENT_TO_PATIENT', 'Sent to Patient'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('assessment_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_patient_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('MODIFIED', 'Modified'), ('REJECTED', 'Rejected'), ('NEEDS_MORE_INFO', 'Needs More Information')], db_index=True, max_length=20)),
                ('clinician_notes', models.TextField(blank=True)),
                ('modified_recommendations', models.JSONField(blank=True, null=True)),
                ('modified_otc_suggestions', models.JSONField(blank=True, null=True)),
                ('modified_monitoring_advice', models.JSONField(blank=True, null=True)),
                ('clinician_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MODERATE', max_length=20)),
                ('requires_urgent_follow_up', models.BooleanField(default=False)),
                ('follow_up_days', models.IntegerField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(auto_now_add=True)),
                ('review_completed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-review_completed_at'],
            },
        ),
    ]
