# Generated by Django 5.2.7 on 2025-12-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassessment',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='conversations.conversationsession'),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentreview',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='assessments.aiassessment'),
        ),
        migrations.AddField(
            model_name='assessmentreview',
            name='clinician',
            field=models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiassessment',
            index=models.Index(fields=['patient', 'status'], name='assessments_patient_44cace_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassessment',
            index=models.Index(fields=['status', 'generated_at'], name='assessments_status_d27858_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreview',
            index=models.Index(fields=['assessment', 'action'], name='assessments_assessm_053bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreview',
            index=models.Index(fields=['clinician', 'review_completed_at'], name='assessments_clinici_4836f8_idx'),
        ),
    ]
