# Generated by Django 5.2.7 on 2026-01-01 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medications', models.JSONField(help_text='Prescribed medications list')),
                ('recommendations', models.JSONField(help_text="Doctor's recommendations")),
                ('warnings', models.JSONField(help_text='Emergency warning signs')),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes")),
                ('pdf_file', models.FileField(blank=True, help_text='PDF prescription document', null=True, upload_to='prescriptions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Patient'), ('PRINTED', 'Printed'), ('FILLED', 'Filled at Pharmacy'), ('EXPIRED', 'Expired'), ('VOIDED', 'Voided')], default='SENT', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Prescription expiry date (typically 30 days)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='assessments.aiassessment')),
                ('clinician', models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patient', 'issued_at'], name='assessments_patient_c1ff6c_idx'), models.Index(fields=['clinician', 'issued_at'], name='assessments_clinici_c58ba0_idx'), models.Index(fields=['status'], name='assessments_status_103e87_idx')],
            },
        ),
    ]
