# Generated by Django 5.2.7 on 2026-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsubscription',
            name='paystack_reference',
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
