# Generated by Django 5.2.7 on 2026-01-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_patientsubscription_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='plan',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.creditpackage'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
