# Generated by Django 5.2.7 on 2025-12-23 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('PROFILE_VIEWED', 'Profile Viewed'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_RECEIVED', 'Message Received'), ('ASSESSMENT_CREATED', 'Assessment Created'), ('ASSESSMENT_VIEWED', 'Assessment Viewed'), ('ASSESSMENT_REVIEWED', 'Assessment Reviewed'), ('ASSESSMENT_MODIFIED', 'Assessment Modified'), ('ASSESSMENT_SENT', 'Assessment Sent'), ('CONVERSATION_STARTED', 'Conversation Started'), ('CONVERSATION_CLOSED', 'Conversation Closed'), ('ESCALATION_TRIGGERED', 'Escalation Triggered'), ('CLINICIAN_ASSIGNED', 'Clinician Assigned'), ('PATIENT_TRANSFERRED', 'Patient Transferred')], db_index=True, max_length=30)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('TERMS_AND_CONDITIONS', 'Terms and Conditions'), ('PRIVACY_POLICY', 'Privacy Policy'), ('DATA_PROCESSING', 'Data Processing Consent'), ('MARKETING', 'Marketing Consent')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('given', models.BooleanField(default=False)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_document_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=50)),
                ('access_type', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('DELETE', 'Delete'), ('EXPORT', 'Export')], max_length=20)),
                ('resource_id', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFailureLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('GROQ_AI', 'Groq AI'), ('TWILIO_API', 'Twilio API'), ('DATABASE', 'Database'), ('EMAIL', 'Email Service'), ('NOTIFICATION', 'Notification Service'), ('REDIS', 'Redis Cache'), ('AUTHENTICATION', 'Authentication')], db_index=True, max_length=30)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('stack_trace', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
