# Generated by Django 5.2.7 on 2025-12-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='data_accessed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicefailurelog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_failures', to='conversations.conversationsession'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_audit_action__74f5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentlog',
            unique_together={('patient', 'consent_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['patient', 'accessed_at'], name='audit_dataa_patient_7c7c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='audit_dataa_user_id_115d85_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefailurelog',
            index=models.Index(fields=['service_type', 'resolved'], name='audit_servi_service_6374f6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefailurelog',
            index=models.Index(fields=['timestamp'], name='audit_servi_timesta_c0e3d1_idx'),
        ),
    ]
