# Generated by Django 5.2.7 on 2025-12-23 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('AWAITING_ACCEPTANCE', 'Awaiting User Agreement'), ('AWAITING_PATIENT_PROFILE', 'Awaiting Profile Info'), ('AI_TRIAGE_IN_PROGRESS', 'AI Triage In Progress'), ('AI_ASSESSMENT_GENERATED', 'Assessment Generated'), ('PENDING_CLINICIAN_REVIEW', 'Pending Clinician Review'), ('CLINICIAN_OVERRIDE', 'Clinician Override'), ('AWAITING_PATIENT_RESPONSE', 'Awaiting Patient Response'), ('DIRECT_MESSAGING', 'Direct Messaging'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], db_index=True, default='INITIAL', max_length=30)),
                ('chief_complaint', models.TextField(blank=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(blank=True, max_length=200)),
                ('ai_questions_asked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triage_completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_clinician_response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clinician', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('PATIENT', 'Patient Message'), ('AI_QUERY', 'AI Question'), ('SYSTEM', 'System Message'), ('CLINICIAN', 'Clinician Response'), ('ESCALATION_ALERT', 'Escalation Alert')], max_length=20)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('twilio_message_sid', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversationsession')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('OPEN_ENDED', 'Open Ended'), ('YES_NO', 'Yes/No'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('SEVERITY', 'Severity Scale')], max_length=20)),
                ('question_order', models.IntegerField()),
                ('patient_response', models.TextField(blank=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('response_processed', models.BooleanField(default=False)),
                ('ai_generated_next_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_questions', to='conversations.conversationsession')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['patient', 'status'], name='conversatio_patient_7db1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['assigned_clinician', 'status'], name='conversatio_assigne_566bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['is_escalated'], name='conversatio_is_esca_ef370b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='conversatio_sender__f913fc_idx'),
        ),
        migrations.AddIndex(
            model_name='triagequestion',
            index=models.Index(fields=['conversation', 'question_order'], name='conversatio_convers_f5e766_idx'),
        ),
    ]
