# Generated by Django 5.2.7 on 2026-01-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
