# Generated by Django 6.0 on 2026-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversationsession_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='mode',
            field=models.CharField(choices=[('AI_ONLY', 'AI Only Chat'), ('CLINICIAN', 'Clinician Consultation')], db_index=True, default='CLINICIAN', max_length=50),
        ),
    ]
