# Generated by Django 6.0 on 2026-01-25 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversationsession_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='mode',
            field=models.CharField(choices=[('UNDECIDED', 'Mode Not Selected'), ('AI_ONLY', 'AI Only Chat'), ('CLINICIAN', 'Clinician Consultation')], db_index=True, default='UNDECIDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('AWAITING_ACCEPTANCE', 'Awaiting User Agreement'), ('MODE_SELECTION', 'Choosing AI or Clinician'), ('AI_ONLY_ACTIVE', 'AI Only - Active Chat'), ('ESCALATION_CONSENT', 'Requesting Clinician Consent'), ('AWAITING_PATIENT_PROFILE', 'Awaiting Profile Info'), ('AI_TRIAGE_IN_PROGRESS', 'AI Triage In Progress'), ('AI_ASSESSMENT_GENERATED', 'Assessment Generated'), ('PENDING_CLINICIAN_REVIEW', 'Pending Clinician Review'), ('CLINICIAN_OVERRIDE', 'Clinician Override'), ('AWAITING_PATIENT_RESPONSE', 'Awaiting Patient Response'), ('DIRECT_MESSAGING', 'Direct Messaging'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], db_index=True, default='INITIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('PATIENT', 'Patient Message'), ('AI_QUERY', 'AI Question'), ('AI_RESPONSE', 'AI Response'), ('SYSTEM', 'System Message'), ('CLINICIAN', 'Clinician Response'), ('ESCALATION_ALERT', 'Escalation Alert')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['mode'], name='conversatio_mode_3e86aa_idx'),
        ),
    ]
